const asyncHandler = require('express-async-handler');
const Make = require('../models/Make');
const Model = require('../models/Model');
const Product = require('../models/Product');
const generateSlug = require('../utils/generateSlug');

// @desc    Fetch all makes
// @route   GET /api/makes
// @access  Public
// @desc    Fetch all makes
// @route   GET /api/makes
// @access  Public
const getMakes = asyncHandler(async (req, res) => {
    const { productType } = req.query;
    let query = { isActive: true };

    if (productType) {
        query.productType = productType;
    }

    const makes = await Make.find(query).sort({ name: 1 });
    res.json(makes);
});

// @desc    Get make by slug
// @route   GET /api/makes/:slug
// @access  Public
const getMakeBySlug = asyncHandler(async (req, res) => {
    const make = await Make.findOne({ slug: req.params.slug, isActive: true });
    if (make) {
        res.json(make);
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

// @desc    Create a make
// @route   POST /api/makes
// @access  Private/Admin
const createMake = asyncHandler(async (req, res) => {
    const { name, logo, description, productType } = req.body;

    const makeExists = await Make.findOne({ name });
    if (makeExists) {
        res.status(400);
        throw new Error('Make already exists');
    }

    // Slug generated by pre-save or util
    var slug = await generateSlug(name, Make);

    const make = await Make.create({
        name,
        logo,
        description,
        productType,
        slug
    });

    res.status(201).json(make);
});

// @desc    Update a make
// @route   PUT /api/makes/:id
// @access  Private/Admin
const updateMake = asyncHandler(async (req, res) => {
    const { name, logo, description, isActive, productType } = req.body;
    const make = await Make.findById(req.params.id);

    if (make) {
        make.name = name || make.name;
        make.logo = logo || make.logo;
        make.description = description || make.description;
        if (isActive !== undefined) make.isActive = isActive;
        if (productType !== undefined) make.productType = productType;

        if (name && name !== make.name) {
            make.slug = undefined; // Will be regenerated
        }

        const updatedMake = await make.save();
        res.json(updatedMake);
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

// @desc    Delete a make
// @route   DELETE /api/makes/:id
// @access  Private/Admin
const deleteMake = asyncHandler(async (req, res) => {
    const make = await Make.findById(req.params.id);

    if (make) {
        // Check if make has models
        // ... (existing logic)
        const models = await Model.find({ make: req.params.id });
        if (models.length > 0) {
            res.status(400);
            throw new Error('Cannot delete make with associated models. Delete models first.');
        }

        const products = await Product.find({ make: req.params.id });
        if (products.length > 0) {
            res.status(400);
            throw new Error('Cannot delete make with associated products.');
        }

        await make.deleteOne();
        res.json({ message: 'Make removed' });
    } else {
        res.status(404);
        throw new Error('Make not found');
    }
});

module.exports = {
    getMakes,
    getMakeBySlug,
    createMake,
    updateMake,
    deleteMake,
};
